FROM scratch
WORKDIR /data

# Args
ARG SOURCE_FILE
ARG CHUNK_SIZE_BYTES
ARG CHUNK_SHA256_HASH
ARG PARENT_FILE
ARG PARENT_FILE_SHA256_HASH
ARG PARENT_FILE_SIZE_BYTES

# Copy files
COPY ${SOURCE_FILE} /data/data_file

# Set labels
LABEL CHUNK_SIZE_BYTES=${CHUNK_SIZE_BYTES}
LABEL CHUNK_SHA256_HASH=${CHUNK_SHA256_HASH}
LABEL PARENT_FILE=${PARENT_FILE}
LABEL PARENT_FILE_SHA256_HASH=${PARENT_FILE_SHA256_HASH}
LABEL PARENT_FILE_SIZE_BYTES=${PARENT_FILE_SIZE_BYTES}