[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "layerstash"
version = "1.0.0"
description = "Tools for archiving files to docker hub"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "attrs",
    "loguru",
    "requests",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "build",
    "nuitka",
    "pytest",
    "ruff",
    "twine",
    "zstandard",
]

[tool.ruff]
target-version = "py310"
line-length = 120
select = [
    "E", # Pycodestyle errors
    "F", # Pyflakes
    "I", # Isort
    "PL", # Pylint
    "UP", # Pyupgrade
]

[tool.pylint.format]
max-line-length = 120

[tool.setuptools]
packages = ["layerstash"]

[project.scripts]
layerstash = "layerstash.main:main"